language: csharp
solution: Duk.EPiServer.Disqus.sln
script:
  - xbuild /p:Configuration=Release;IsTravisBuild=true Duk.EPiServer.Disqus.sln
  - mono ../.nuget/NuGet.exe pack ./Duk.EPiServer.Disqus.travis.nuspec  -Properties Configuration=Release -OutputDirectory ../packages.addons
  - mono ../.nuget/NuGet.exe pack ./Duk.EPiServer.Disqus.UI.travis.nuspec  -Properties Configuration=Release -OutputDirectory ../packages.addons