language: csharp
solution: Duk.EPiServer.Disqus.sln
script:
  - xbuild /p:Configuration=Release Duk.EPiServer.Disqus.sln
  - rm -rf ./packages.addons
  - mkdir -p ./packages.addons
  - mono ./.nuget/NuGet.exe pack ./Duk.EPiServer.Disqus/Duk.EPiServer.Disqus.nuspec  -Properties Configuration=Release -OutputDirectory ./packages.addons
  - mono ./.nuget/NuGet.exe pack ./Duk.EPiServer.Disqus.UI/Duk.EPiServer.Disqus.UI.nuspec  -Properties Configuration=Release -OutputDirectory ./packages.addons